changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - fix
    - title: Other Changes
      labels:
        - '*'
