exec_timeout_secs: 600

functions:
  checkout:
    - command: git.get_project
      params:
        directory: src
  install:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          set -e
          set -x

          export PATH=/opt/devtools/node16/bin:$PATH
          npm ci
  check:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          set -e
          set -x

          export PATH=/opt/devtools/node16/bin:$PATH
          npm run compile
          npm run check
  test:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        env:
          OKTA_TEST_CONFIG: ${okta_test_config}
          OKTA_TEST_CREDENTIALS: ${okta_test_credentials}
          AZURE_TEST_CONFIG: ${azure_test_config}
          AZURE_TEST_CREDENTIALS: ${azure_test_credentials}
          DISTRO_ID: ${distro_id}
        script: |
          set -e
          set -x

          # Google Chrome exists on the Ubuntu hosts but is very slow to start,
          # so webdriverio times out when trying to start it *but* then later
          # never cleans up the spawned chrome process so that the mocha process
          # just keeps timing out.
          if echo "${distro_id}" | grep -q ubuntu; then export SKIP_REGULAR_BROWSER_TESTING=true; fi

          export PATH=/opt/devtools/node16/bin:$PATH
          npm run test-ci
  test_electron:
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        env:
          OKTA_TEST_CONFIG: ${okta_test_config}
          OKTA_TEST_CREDENTIALS: ${okta_test_credentials}
          AZURE_TEST_CONFIG: ${azure_test_config}
          AZURE_TEST_CREDENTIALS: ${azure_test_credentials}
          DISTRO_ID: ${distro_id}
        script: |
          set -e
          set -x

          export PATH=/opt/devtools/node16/bin:$PATH
          npm run test-electron

tasks:
  - name: test
    commands:
      - func: checkout
      - func: install
      - func: test
  - name: test_electron
    commands:
      - func: checkout
      - func: install
      - func: test_electron
  - name: check
    commands:
      - func: checkout
      - func: install
      - func: check

buildvariants:
  - name: ubuntu_x64_test
    display_name: 'Ubuntu 20.04 x64'
    run_on: ubuntu2004-small
    tasks:
      - test
      - test_electron
      - check
  - name: macos_x64_test
    display_name: 'macOS 11.00 x64'
    run_on: macos-11-gui
    tasks:
      - test
      - test_electron
  - name: macos_arm64_test
    display_name: 'macOS 11.00 arm64'
    run_on: macos-11-arm64-gui
    tasks:
      - test
      - test_electron
  - name: windows_x64_test
    display_name: 'Windows x64'
    run_on: windows-vsCurrent-small
    tasks:
      - test
      - test_electron
