name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci --ignore-engines

      - name: Compile
        run: npm run compile

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Read Version
        id: get-version
        run: |
          echo "package_version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Find Release PR
        id: find-pull-request
        uses: juliangruber/find-pull-request-action@48b6133aa6c826f267ebd33aa2d29470f9d9e7d0 # 1.9.0
        with:
          branch: ${{ github.ref }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@9234b8714dda9a08f3d1df5b2a6a3abd7b695353 # 1.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
          method: squash

      - name: Publish Github Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # 1.14.0
        with:
          generateReleaseNotes: true
          name: ${{ steps.get-version.outputs.package_version }}
          commit: main
          tag: ${{ steps.get-version.outputs.package_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
